---
version: "3"

################################################################################
# Tasks
################################################################################

tasks:
  default:
    deps:
      - main:tests
  main:lint:
    deps:
      - md:lint
      - python:format
      - python:lint
  main:tests:
    deps:
      - main:lint
      - molecule:test

  ################################################################################
  # OS
  ################################################################################

  os:install-dependencies:
    desc: Install dependencies of the OS if running in github actions
    run: once
    cmds:
      - |
        if [ ! -z "${GITHUB_ACTIONS}" ]; then
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
        fi

  ################################################################################
  # Markdown
  ################################################################################

  md:lint:
    desc: Lint Markdown files
    deps:
      - task: uv:install-dependencies
    cmds:
      - uv run pymarkdownlnt --disable-rules MD013 scan .

  ################################################################################
  # Python
  ################################################################################

  python:lint:
    desc: Lint Python code
    deps:
      - task: uv:install-dependencies
    cmds:
      - uv run ruff check *.py

  python:format:
    desc: Format Python files
    deps:
      - task: uv:install-dependencies
    cmds:
      - uv run ruff format *.py

  ################################################################################
  # uv
  ################################################################################

  uv:install-dependencies:
    run: once
    desc: Install dependencies managed by uv
    cmds:
      - uv sync

  uv:update-dependencies:
    desc: Update all dependencies managed by uv to their newest versions
    cmds:
      - uv lock --upgrade

  ################################################################################
  # Ansible / Molecule
  ################################################################################

  molecule:test:
    desc: Run molecule tests
    deps:
      - task: uv:install-dependencies
    cmds:
      - uv run molecule test
    env:
      HCLOUD_TOKEN:
        sh: "[[ -z $HCLOUD_TOKEN ]] && op --account pixel-combo.1password.com item get yvgxtaa6cptielkwjqispregdu --fields password --reveal || echo ${HCLOUD_TOKEN}"

  ansible:galaxy:release:
    desc: Create a new release on Ansible Galaxy
    deps:
      - task: uv:install-dependencies
    cmds:
      - uv run ansible-galaxy role import --api-key $GALAXY_API_KEY $(echo $REPO | cut -d/ -f1) $(echo $REPO | cut -d/ -f2)
    requires:
      vars: [GALAXY_API_KEY, REPO]

  ################################################################################
  # Other
  ################################################################################

  role:update-package-urls:
    desc: Update 'vars/package_url.yaml'
    deps:
      - task: uv:install-dependencies
    cmds:
       - uv run ./get-package-urls.py > vars/package_url.yaml
