---
- name: Include Package URL's
  ansible.builtin.include_vars:
    file: vars/package_url.yaml

# Install agent
- name: Include setup
  ansible.builtin.include_tasks: "setup.yml"

# configured nessusd.rules file
- name: Create nessusd.rules file
  ansible.builtin.template:
    src: nessusd.rules.j2
    dest: "{{ nessus_install_dir }}/etc/nessus/nessusd.rules"
    mode: "0644"
  when: nessus_agent_rules | length > 0

# Check agent and start service
- name: Check for Nessus installation
  ansible.builtin.stat:
    path: "{{ nessus_install_dir }}"
  register: stat_result

- name: Check Nessus Agent
  ansible.builtin.command: "{{ nessus_agent_path }} agent status"
  become: true
  changed_when: false
  ignore_errors: true
  register: check_result

- name: Make sure a service is running
  ansible.builtin.systemd:
    state: started
    name: "{{ nessus_agent_service_name }}"

- name: Link Nessus Agent to Nessus Manager # noqa no-changed-when
  ansible.builtin.command: "{{ nessus_agent_path }} agent link --host={{ nessus_agent_host }} --port={{ nessus_agent_port }} --key={{ nessus_agent_key }} --groups={{ nessus_agent_group }}"
  become: true
  when: check_result.stdout is search('Not linked to') and nessus_agent_key | length > 0
