---
- name: Converge
  hosts: all
  become: true
  vars:
    nessus_agent_rules:
      default: accept
      plugin_reject:
        - 33851
      plugin_accept:
        - 10000-40000
      reject:
        - 10.42.123.0/24
      accept:
        - 10.0.0.0/24

  roles:
    - ansible-role-tenable-agent
