---
dependency:
  name: galaxy
driver:
  name: molecule_hetznercloud
platforms:
  - name: "tenable-agent-${USER:-noname}-${MOLECULE_DISTRO:-debian-11}"
    server_type: cx23
    image: ${MOLECULE_DISTRO:-debian-11}
provisioner:
  name: ansible