---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  # See https://github.com/ansible-community/ansible-lint/issues/1329
  # Exclude molecule/default/ because of this issue
  ansible-lint --exclude=molecule/default/

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge-rpm.yml}
