---
dependency:
  name: galaxy
driver:
  name: hetznercloud
platforms:
  - name: "ansible-role-tenable-agent-instance-${USER:-noname}-${MOLECULE_DISTRO:-debian-11}"
    server_type: cx11
    image: ${MOLECULE_DISTRO:-debian-11}
provisioner:
  name: ansible
lint: |
  pipenv run yamllint .
  # See https://github.com/ansible-community/ansible-lint/issues/1329
  # Exclude molecule/default/ because of this issue
  pipenv run ansible-lint --exclude=molecule/default/
