---
dependency:
  name: galaxy
lint: |
  pipenv run yamllint .
  # See https://github.com/ansible-community/ansible-lint/issues/1329
  # Exclude molecule/default/ because of this issue
  pipenv run ansible-lint --exclude=molecule/default/
driver:
  name: hetznercloud
platforms:
  - name: "instance-${USER}-${GITHUB_SHA}-${MOLECULE_DISTRO:debian-11}"
    server_type: cx11
    image: ${MOLECULE_DISTRO:-debian-11}
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge-apt.yml}
